version: '3.8' # Specifies the docker-compose file format version

services:
  # --- MariaDB for OLTP (Online Transaction Processing) ---
  mariadb_oltp:
    image: mariadb:10.11 # Using a specific recent, stable version of MariaDB
    container_name: mushroom_mariadb_oltp
    restart: unless-stopped # Automatically restarts the container unless explicitly stopped
    environment:
      # These environment variables are used by the MariaDB image on first run
      MARIADB_ROOT_PASSWORD: ${MARIADB_OLTP_ROOT_PASSWORD} # Gets value from .env file
      MARIADB_DATABASE: mushroom_oltp_db # Creates this database on first startup
    ports:
      - "3307:3306" # Maps port 3307 on your Zorin OS to port 3306 inside the container
    volumes:
      - mariadb_oltp_data:/var/lib/mysql # Persists database data outside the container
    networks:
      - mushroom_network # Connects this service to a custom network

  # --- MariaDB for OLAP (Online Analytical Processing) ---
  # For simplicity, we'll use another standard MariaDB instance.
  # For true ColumnStore, you'd need a specific image/setup.
  mariadb_olap:
    image: mariadb:10.11
    container_name: mushroom_mariadb_olap
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_OLAP_ROOT_PASSWORD} # Gets value from .env file
      MARIADB_DATABASE: mushroom_olap_db
    ports:
      - "3308:3306"
    volumes:
      - mariadb_olap_data:/var/lib/mysql
    networks:
      - mushroom_network

  # --- Redis for Caching / Data Passing ---
  redis:
    image: redis:latest # Using the latest stable Redis image
    container_name: mushroom_redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Standard Redis port
    volumes:
      - redis_data:/data # Persists Redis data (optional for pure cache)
    networks:
      - mushroom_network

  # --- Adminer for Database Management (Web UI) ---
  adminer:
    image: adminer:latest
    container_name: mushroom_adminer
    restart: unless-stopped
    ports:
      - "8081:8080" # Using 8081 on host to avoid conflict if you run Airflow webserver on 8080
    depends_on: # Ensures databases are likely ready before Adminer starts
      - mariadb_oltp
      - mariadb_olap
    networks:
      - mushroom_network

# --- Named Volumes for Data Persistence ---
# These ensure your data is saved even if containers are stopped/removed
volumes:
  mariadb_oltp_data:
  mariadb_olap_data:
  redis_data:

# --- Custom Network ---
# Allows containers to communicate with each other using their service names as hostnames
networks:
  mushroom_network:
    driver: bridge # Standard Docker network driver